version: '3.5'
services:
  api1: &api
    image: docker.io/akitaonrails/rinhabackend-crystal:latest
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/postgres?initial_pool_size=10&max_pool_size=25
      DEV_HOST: "0.0.0.0"
    hostname: api1
    depends_on:
      - postgres
    expose:
      - "3000"
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.5GB'

  api2:
    <<: *api
    hostname: api2

  nginx: # Load Balancer
    image: docker.io/nginx:latest
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: '0.3GB'

  postgres: # Banco de dados
    image: docker.io/postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.60'
          memory: '1.7GB'
